export const Actions = {
    REQUESTING_LOGIN: 'REQUESTING_LOGIN',
    RECEIVE_LOGIN: 'RECEIVE_LOGIN',
    RECEIVE_LOGIN_ERROR: 'RECEIVE_LOGIN_ERROR',
    REQUESTING_LOGOUT: 'REQUESTING_LOGOUT',
    RECEIVE_LOGOUT: 'RECEIVE_LOGOUT',
    RECEIVE_LOGOUT_ERROR: 'RECEIVE_LOGOUT_ERROR',
    REQUESTING_CHECK_AUTHENTICATION: 'REQUESTING_CHECK_AUTHENTICATION'
}